swagger: '2.0'
info:
  title: My API
  description: API for user registration, login, and data retrieval
  version: '1.0'
paths:
  /login:
    post:
      summary: User login
      parameters:
        - name: username
          in: body
          required: true
          schema:
            type: string
        - name: password
          in: body
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful login
          schema:
            type: object
            properties:
              jwtToken:
                type: string
  /register:
    post:
      summary: User registration
      parameters:
        - name: username
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
              password:
                type: string
              email:
                type: string
      responses:
        '200':
          description: User registered successfully
  /data:
    get:
      summary: Fetch data from public API with filtering
      parameters:
        - name: category
          in: query
          required: false
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Data fetched successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/DataEntry'
definitions:
  DataEntry:
    type: object
    properties:
      API:
        type: string
      Description:
        type: string
      Auth:
        type: string
      HTTPS:
        type: boolean
      Cors:
        type: string
      Link:
        type: string
